### PR TITLE
Use 4 spaces for indentation

### PR DESCRIPTION
**Pull request by youtux**
As recommended by PEP8: https://www.python.org/dev/peps/pep-0008/#indentation

### CODE REVIEW

**Comment by robinandeer** [comment]
Hi, thanks for contributing!

I'm aware of the stance that PEP8 has on indentation. I try to keep to the 80 char limit per line. It makes sense to me. Combined with 4 spaces per indent, however, there's just a lot of whitespace that I think rather makes the code less readable in the end.

I would love to hear your opinions and then I will consider merging your PR.

**Comment by youtux** [comment]
Well, if I had to choose which rule to keep between the "79 chars" limit and the "4 space indent" I'd pick the latter. Anyway, I usually try as much as I can to follow both rules in my projects, and many times I have to split a line into two. However I noticed that actually this makes my code more readable.

Moreover, every time I see a 2-space indented python source I feel like there's something wrong :)

**Comment by robinandeer** [comment]
You know what; if I want this project to be based on best practices I should probably follow the standards as much as possible by default. I guess it won't be all that difficult for users to convert between 2/4 spaces indents either.

I'll merge this and see if I can notice the benefits you are talking about :wink:

**Comment by youtux** [comment]
Thank you! Much appreciated.

**Pull request merged**
